"""Add batch_id to slots

Revision ID: 16bf872410ae
Revises: 94a593f0d5f9
Create Date: 2026-04-25 16:11:09.738155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16bf872410ae'
down_revision: Union[str, Sequence[str], None] = '94a593f0d5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_slots', sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_booking_slots_batch_id'), 'booking_slots', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_slots_batch_id'), table_name='booking_slots')
    op.drop_column('booking_slots', 'batch_id')
    # ### end Alembic commands ###
