"""cascade group meeting delete

Revision ID: 94a593f0d5f9
Revises: cced646d7655
Create Date: 2026-04-25 14:28:59.750216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a593f0d5f9'
down_revision: Union[str, Sequence[str], None] = 'cced646d7655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_booking_slots_group_meeting_id_group_meetings'), 'booking_slots', type_='foreignkey')
    op.create_foreign_key(None, 'booking_slots', 'group_meetings', ['group_meeting_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_slots', type_='foreignkey')
    op.create_foreign_key(op.f('fk_booking_slots_group_meeting_id_group_meetings'), 'booking_slots', 'group_meetings', ['group_meeting_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
