"""description of changes

Revision ID: abbe73942ed6
Revises: cdc210d51daf
Create Date: 2026-04-24 12:16:07.940928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abbe73942ed6'
down_revision: Union[str, Sequence[str], None] = 'cdc210d51daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('status', postgresql.ENUM('CONFIRMED', 'CANCELLED', name='reservationstatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
